    const weatherConditionsConverter = {
      "200": "Orage avec pluie légère",
      "201": "Orage avec pluie",
      "202": "Orage avec fortes pluies",
      "210": "Orage léger",
      "211": "Orage",
      "212": "Orage fort",
      "221": "Orage déchiqueté",
      "230": "Orage avec bruine légère",
      "231": "Orage avec bruine",
      "232": "Orage avec fortes bruines",
      "300": "Bruine légère",
      "301": "Bruine",
      "302": "Forte bruine",
      "310": "Pluie fine",
      "311": "Pluie",
      "312": "Pluie intense",
      "313": "Pluie très forte",
      "314": "Pluie extrême",
      "321": "Pluie verglaçante",
      "500": "Pluie fine et intermittente",
      "501": "Pluie intermittente",
      "502": "Pluie intense et intermittente",
      "503": "Pluie intermittente déchiquetée",
      "504": "Pluie extrême",
      "511": "Pluie verglaçante",
      "520": "Pluie légère intermittente",
      "521": "Averses de pluie",
      "522": "Averses de pluie intense",
      "531": "Averses de pluie déchiquetées",
      "600": "Légère neige",
      "601": "Neige",
      "602": "Forte neige",
      "611": "Grésil",
      "612": "Grésil léger",
      "613": "Grésil",
      "615": "Pluie et neige légères",
      "616": "Pluie et neige",
      "620": "Légère chute de neige",
      "621": "Chute de neige",
      "622": "Forte chute de neige",
      "701": "Brume",
      "711": "Fumée",
      "721": "Brume",
      "731": "Tourbillons de sable/poussière",
      "741": "Brouillard",
      "751": "Sable",
      "761": "Poussière",
      "762": "Cendres volcaniques",
      "771": "Rafales",
      "781": "Tornade",
      "800": "Ciel dégagé",
      "801": "Quelques nuages 11-25%",
      "803": "Nuages morcelés 51-84%",
      "804": "Nuages couverts 85-100%" 
    }

 export default weatherConditionsConverter